# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

# default: &default
#   adapter: mysql2
#   pool: 5
#   timeout: 5000

default: &default
    adapter: mysql2
    encoding: utf8
    reconnect: false
    secure_auth: false
    pool: 5


development:
  <<: *default
  database: db/development.mysql2


test:
  <<: *default
  database: db/development.mysql2

production:
  <<: *default
  database: db/production.mysql2

  # db/production.sqlite3

  # db/test.sqlite3

  # db/development.sqlite3

# development:
#   adapter: mysql2
#   database: myapp_development
#   pool: 20
#   encoding: utf8
#   username: mydbuser
#   password: mydbpassword
#   host:  localhost

# test:
#   adapter: mysql2
#   database: myapp_test
#   pool: 20
#   encoding: utf8
#   username: mydbuser
#   password: mydbpassword
#   host:  localhost

# production:
#   adapter: mysql2
#   database: myapp
#   pool: 20
#   encoding: utf8
#   username: mydbuser
#   password: mydbpassword
#   host:  mypublichost.com
